// This file is auto-generated by update-backend-url.js

export const BACKEND_URL = 'https://eb74-2607-f010-2a7-1023-451b-48e7-622a-1230.ngrok-free.app';
export const TAGGER_URL  = 'https://95ce-2607-f010-2a7-1023-451b-48e7-622a-1230.ngrok-free.app';
