// This file is auto-generated by update-backend-url.js

export const BACKEND_URL = 'https://46e2-2607-f010-2a7-18-dcb-e1ce-38df-bee8.ngrok-free.app';
export const TAGGER_URL  = 'https://77a3-2607-f010-2a7-18-dcb-e1ce-38df-bee8.ngrok-free.app';
