// This file is auto-generated by update-backend-url.js

export const BACKEND_URL = 'https://2bf1-2603-8001-7300-da63-6173-1884-2fa1-6c0b.ngrok-free.app';
export const TAGGER_URL  = 'https://52cf-2603-8001-7300-da63-6173-1884-2fa1-6c0b.ngrok-free.app';
